Todo App UI update
bappa-coco/todo-app pull request #3
Opened 2023-10-04 18:58 UTC by soumitra-technicise

2023-10-10 12:06 UTC, bonno123 requested changes

2023-10-10 12:06 UTC, bonno123 commented on src/Components/Form.tsx
> +      window.location.reload();
can you please explain why you have used reload here ?

2023-10-10 12:06 UTC, bonno123 commented on src/Components/Form.tsx
>            onKeyDown={handleKeyDown}
why handleKeydown ?

2023-10-10 12:06 UTC, bonno123 commented on src/Components/TodoCard.tsx
> +            <CardHeader title="Create your todo list" />
extract all strings form here to some constants like

`const formTitle = 'Create your todo list'`

and use it like `title={formTitle}`

2023-10-10 12:06 UTC, bonno123 commented on src/Components/TodoList.tsx
> +  const handleClickOpen = () => {
could you please change the handlers more descriptive like

`closeEditTodoDialog` or `openEditTodoDialog`

2023-10-10 12:06 UTC, bonno123 commented on src/Components/TodoList.tsx
> +        open={open}
change the variable name `shouldOpenDialog`
```suggestion
        open={shouldOpenDialog}
```

2023-10-10 12:10 UTC, bonno123 requested changes
plaese look into the changes

2023-10-10 17:11 UTC, soumitra-technicise commented on src/Components/TodoCard.tsx
> +            <CardHeader title="Create your todo list" />
ok No problem I am using this approch

2023-10-10 17:38 UTC, soumitra-technicise commented on src/Components/Form.tsx
> +      window.location.reload();
to handle autofocus here i am using window.location.reload(). Now i am using e.preventDefault(); to handle this.

2023-10-10 17:49 UTC, soumitra-technicise commented on src/Components/Form.tsx
>            onKeyDown={handleKeyDown}
handleKeyDown is a function which will be called only when user write anything into input form and press the enter button.

2023-10-10 18:15 UTC, soumitra-technicise commented on src/Components/TodoList.tsx
> +  const handleClickOpen = () => {
which one you like to change the function name or the state variable name?

2023-10-12 07:02 UTC, abskj commented
you still have package-lock.json and yarn.lock files both. Please use only one.
Also specify which node version and package manager this should run on for clarity.

2023-10-12 07:14 UTC, soumitra-technicise commented
[image: image.png]
I think you are not pulling the latest version as I see in my code base
there is only yarn.lock file. I also attached the screenshot of my latest
code base. Please pull the main and see. Thanks.

On Thu, Oct 12, 2023 at 12:32 PM Abhishek Jha ***@***.***>
wrote:

> you still have package-lock.json and yarn.lock files both. Please use only
> one.
> Also specify which node version and package manager this should run on for
> clarity.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/bappa-coco/todo-app/pull/3#issuecomment-1759042518>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AYTNEHFWC7C2TF7TKCWYEH3X66IYTANCNFSM6AAAAAA5TC2NQY>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-10-31 17:54 UTC, soumitra-technicise commented
@abskj @bonno123 what is status of the pull request???

2023-11-02 18:13 UTC, bonno123 requested changes

2023-11-02 18:13 UTC, bonno123 commented on src/Components/TodoList.tsx
> +  const handleClickOpen = () => {
All the functions should be a properly named function (Don't use the arrow functions; since arrow functions are introduced in JS for a specific purpose). And name the function properly based on what it does ( not like handleXxx because in a bigger code base it would not be manageable).

2023-11-02 18:13 UTC, bonno123 commented on src/Components/Form.tsx
>    const handleKeyDown = (e: React.KeyboardEvent) => {
I think You don't need to explicitly **handle key down** for a form. when we submit a form either with the submit button or by pressing enter the event **bubbles up** to the root component. Then handle the event on the parent component then prevent the default behaviour of that event.

2023-11-02 18:13 UTC, bonno123 commented on src/Components/Form.tsx
>    const handleKeyDown = (e: React.KeyboardEvent) => {
FYI :
React use SyntheticEvent:  read how react event propagates.
and also read the types of event propagation in JS (bubbling and capturing).

2023-11-03 16:37 UTC, soumitra-technicise commented on src/Components/Form.tsx
>    const handleKeyDown = (e: React.KeyboardEvent) => {
As per your requirement I am removeing the handleKeyDown function.

2023-11-16 15:09 UTC, merged